### ISSUE TITLE
Getting this error even for v4.52Error: The terraform-provider-aws_v4.0.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by harsharno** [hashicorp/terraform-plugin-sdk#1133] opened 2023-02-01 11:37 UTC
Stack trace from the terraform-provider-aws_v4.0.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 179 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ecs.expandClusterConfiguration({0xc001e219c0, 0x8905e17, 0xc0028cd658})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ecs/cluster.go:564 +0x113
github.com/hashicorp/terraform-provider-aws/internal/service/ecs.resourceClusterCreate(0xc001b71500, {0x75fbb40, 0xc0001a4a80})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ecs/cluster.go:201 +0x351
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x7333760, {0x986c358, 0xc001b357c0}, 0x2, {0x75fbb40, 0xc0001a4a80})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000c420e0, {0x986c358, 0xc001b357c0}, 0xc001b735f0, 0xc001b71380, {0x75fbb40, 0xc0001a4a80})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c030, {0x986c358, 0xc001b357c0}, 0xc001b7c780)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000314800, {0x986c400, 0xc001b75e60}, 0xc001e0dea0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x869ca60, 0xc000314800}, {0x986c400, 0xc001b75e60}, 0xc001b0ff20, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00064ea80, {0x995e0c0, 0xc000668000}, 0xc0002dfc00, 0xc00062a810, 0xeea5460, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00064ea80, {0x995e0c0, 0xc000668000}, 0xc0002dfc00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-aws_v4.0.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by bflad** [comment] 2023-02-01 14:11
Closing as a duplicate of #1134

**Closed by bflad** 2023-02-01 14:11 UTC
Labels: bug
