### ISSUE TITLE
Behaviour of `terraform providers schema` command for computed fields

### ISSUE THREAD

**Issue by rahulrj** [hashicorp/terraform-plugin-sdk#1186] opened 2023-04-06 02:02 UTC
### SDK version
terraform-plugin-sdk - v2.20.0
Terraform v1.4.4 on darwin_arm64

### Relevant provider source code

I have a nested field in the schema,
```go
"topic_schemas": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"schema": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Kafka topic schema in string format",
						},
						"schema_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Internal schema ID",
						},
					},
				},
			},
```

### Expected behavior
When i run `terraform providers schema -json` on this provider schema, this field should appear under `block_types` section in the JSON schema representation as mentioned here
https://developer.hashicorp.com/terraform/cli/commands/providers/schema

### Actual behavior
When i run `terraform providers schema -json` on this provider schema, i get this field in `attributes` section of the JSON file
```
"topic_schemas": {
                "type": [
                  "list",
                  [
                    "object",
                    {
                      "schema": "string",
                      "schema_id": "string"
                    }
                  ]
                ],
                "description_kind": "plain",
                "computed": true
              }
            },
```

However, when i add `Optional:true` in `topic_schemas` in the provider code, the generated JSON shows it correctly in `block_types section`. Is this a bug? Since `topic_schemas` is a nested block, shouldn't it always go into the block_types section? Why does `Optional:true` matter here?

**Comment by bflad** [comment] 2023-04-10 17:45
Hi @rahulrj 👋 Thank you for raising this and sorry for the unexpected behavior.

Over in https://github.com/hashicorp/terraform/issues/33006 this was answered, but to provide some additional context, this is _unfortunately_ expected behavior that is protected by compatibility promises. This particular provider SDK has had this behavior since it was split off from the Terraform core codebase and cannot be updated without a major version increase.

You _may_ be able to workaround this particular SDK behavior in your provider code by explicitly setting the [`schema.Schema` type `ConfigMode` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.ConfigMode) to `schema.SchemaConfigModeBlock`, however do note that if it is an existing attribute, that adjusting that setting will create a breaking change for practitioner configurations referencing the value of that attribute. When that setting is not set, the automatic behavior for "computed only" blocks is to make them an object. When that setting is set to block, the value becomes of list or set of objects. Especially with sets, Terraform does not support _direct_ index references into those values (rather they must be referenced via expressions such as `for` or `for_each`), so it is important to understand the consequences of switching the setting.

In terraform-plugin-framework, the schema definitions are very explicit to avoid this unexpected automatic behavior. For example, you cannot configure a "computed only" block, but rather only a block with all computed values (or maybe preferably, a computed nested attribute, which avoids the nuances around blocks in Terraform).

Since there are no current plans for a next major version of this SDK and the behavior is already resolved by migrating to terraform-plugin-framework, I'm going to close this issue. Thanks again for bringing this up.

**Closed by bflad** 2023-04-10 17:45 UTC
Labels: bug, terraform-plugin-framework

**Comment by rahulrj** [comment] 2023-04-12 01:31
@bflad thanks for clarifying the behavior.
According to the docs, i cant set `ConfigMode` for a Computed field
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.ConfigMode

> When Computed is set without Optional, the attribute is not settable
> 	// in configuration at all and so SchemaConfigModeAttr is the automatic
> 	// behavior, and SchemaConfigModeBlock is not permitted.

I get an error on setting this field for computed attributes
```
╷
│ Error: InternalValidate
│
│   with provider["registry.terraform.io/hashicorp/nuage"],
│   on main.tf line 1, in provider "nuage":
│    1: provider "nuage" {}
│
│ Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│
│ 1 error occurred:
│ 	* resource nuage_te: hybrid_store_config: ConfigMode of block cannot be used for computed schema
│
│

```

So, what do you mean when you say?

> You may be able to workaround this particular SDK behavior in your provider code by explicitly setting the [schema.Schema type ConfigMode field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.ConfigMode) to schema.SchemaConfigModeBlock
