### ISSUE TITLE
TypeSet duplicates trailing key when element added higher up

### ISSUE THREAD

**Issue by jacobbednarz** [hashicorp/terraform-plugin-sdk#589] opened 2020-09-21 22:39 UTC
Within a Terraform provider, we are planning on using a [TypeSet](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset) to represent a series of unordered IDs. The usage looks roughly like this:

```hcl
role_ids = ["a", "b", "c"]
```

However, when a new record is added anywhere except the end of the set, it shows it is duplicating the last entry while leaving the remainder unchanged. 

After creating the initial set and then given `role_ids = ["d", "a", "b", "c"]` I would expect the output to be:

```diff
  role_ids = [
+   "d", 
    "a", 
    "b", 
    "c"
  ]
```

However, the actual is this:

```diff
   role_ids = [
    "a", 
    "b", 
    "c",
+   "c", 
  ]
```

### Steps to reproduce

1. Create a schema field with `TypeSet`
1. Add a couple of test values 
1. Apply the change 
1. Add an element to the start of the set
1. Attempt to apply

Duplication should be visible.

### Versions

I have tried this with terraform-plugin-sdk v2.0.3 and master and both are exhibiting the issue using the Terraform version 0.12.29

**Comment by bflad** [comment] 2022-03-21 16:49
Hi @jacobbednarz 👋  Thank you for reporting this and apologies for the delayed response.

There have been a lot of changes in Terraform CLI and terraform-plugin-sdk/v2 since this was originally raised. When attempting to reproduce this on the most recent versions of both (Terraform CLI v1.1.7 and terraform-plugin-sdk/v2@v2.12.0), I'm not able to do so given the following schema:

```go
"example_typeset_attr": {
	Type:     schema.TypeSet,
	Optional: true,
	Elem: &schema.Schema{
		Type: schema.TypeString,
	},
},
```

And Terraform configuration:

```terraform
example_typeset_attr = ["d", "a", "b", "c"] # Previously ["a", "b", "c"]
```

Here's the output I see when attempting to add the new set element:

```
      ~ example_typeset_attr = [
          + "d",
            # (3 unchanged elements hidden)
        ]
```

Since this appears to be working as expected now, I'm going to close this out. If you do happen to still be having issue and can provide a reproduction on more recent versions of everything along with the relevant resource code, please open a new issue we can take a fresh look. Thank you.

**Closed by bflad** 2022-03-21 16:49 UTC
Labels: subsystem/types
