### ISSUE TITLE
Optional fields on nested schemas

### ISSUE THREAD

**Issue by xanderflood** [hashicorp/terraform-plugin-sdk#258] opened 2019-11-20 21:03 UTC
Consider the following resource schema:

```golang
var dataSourceQuery = &schema.Resource{
	Read:   queryRead,
	Schema: querySchema,
}

var querySchema = map[string]*schema.Schema{
	"sort_fields": &schema.Schema{
		Type:     schema.TypeList,
		Optional: true,
		ForceNew: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"field_name": &schema.Schema{
					Type:     schema.TypeString,
					Required: true,
				},
				"ascending": &schema.Schema{
					Type:     schema.TypeBool,
					Optional: true,
					Default:  nil,
				},
			},
		},
	},
}

func queryRead(d *schema.ResourceData, m interface{}) error {
	spew.Dump(d.Get("sort_fields"))
	spew.Dump(d.Get("sort_fields.0.field_name"))
	spew.Dump(d.Get("sort_fields.0.ascending"))

	return nil
}
```

Now I apply the apply the following config:

```hcl
resource "query" "test" {
	sort_fields {
		field_name = "something"
	}
}
```

The output I get in the terminal is this:
```
([]interface {}) (len=1 cap=1) {
 (map[string]interface {}) (len=2) {
  (string) (len=8) "field_name": (string) (len=8) "something",
  (string) (len=9) "ascending": (bool) false
 }
}
(string) (len=8) "something"
(bool) false
```

### What's the expected behavior?
If a field is declared as optional at the top level of a resource, it's possible to determine whether or not the field was actually set, for instance using `GetOk`. I would expect to have the same behavior for fields defined nested at lower levels. In other words, I would've expected to see:
```
([]interface {}) (len=1 cap=1) {
 (map[string]interface {}) (len=2) {
  (string) (len=8) "field_name": (string) (len=8) "something",
 }
}
(string) (len=8) "something"
(interface{}) nil
```

so that I'm able to tell the whether the user left the `ascending` field unset, or rather set the `ascending` field explicitly to false. My feeling is that one of the following should happen:
1. This should be changed
2. The "Best Practices" section of the Custom Terraform Provider docs should indicate that it's prudent to _always_ specify default values for fields on nested schemas, in order to be explicit about which value will be filled in when it isn't specified
3. The docs should at least call out this difference between top-level and nested fields explicitly and explain the rationale for it (this may already be in the docs, but I wasn't able to find it)

My feeling is that option 1 is valuable. There are lots of reasons why it'd be _necessary_ to have this information. In particular, it's a good practice IMO for a TF provider to rarely apply default values, so that backend APIs have the opportunity to apply their _own_ defaults when fields are omitted.

**Comment by radeksimko** [comment] 2019-12-12 15:48
Hi @xanderflood 
I believe that what you are basically asking for is support for `null`, i.e. ability to express and reflect empty/undefined value. This practically isn't possible in 0.11 type system. While 0.12 makes it possible, but the SDK doesn't expose that, which came as a cost for retaining backwards compatibility with 0.11.

We are however in active discussion about deprecating 0.11 and introducing support for 0.12 features in the SDK, such as the new type system (inc. `null`).

With that said I'm going to close this as a duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/102 since that issue covers all types and it will allow us to keep discussion in a single place. Let me know if I'm mistaken about anything and I'm happy to reopen.

**Closed by radeksimko** 2019-12-12 15:48 UTC
Labels: enhancement, protocol-5-only

**Comment by xanderflood** [comment] 2019-12-16 21:56
@radeksimko My sense is that I'm referring to something slightly different, although I definitely don't have a deep enough understanding of the Terraform core to know for sure.

The reason that doesn't quite sound right is because the behavior I expect _is supported_ by the SDK at the top level, just not for nested fields. That is, (if I'm understanding the situation with nulls correctly) an unset field at the top level encodes a `null`, while an unset nested field encodes the zero value for its type. My guess was that this is a real difference in the data being parsed out of the config and sent _to_ the provider, rather than something that happens inside the provider or SDK. Am I understanding that correctly?
