### ISSUE TITLE
Optional and Computed fields cannot be updated to an empty string

### ISSUE THREAD

**Issue by kayrus** [hashicorp/terraform-plugin-sdk#173] opened 2019-08-27 08:29 UTC
### Terraform Version

```
Terraform v0.12.7
+ custom provider, which uses the v0.12.7 SDK
```

### Terraform Configuration Files

```go
                        "optional_computed_string": {
                                Type:     schema.TypeString,
                                Optional: true,
                                Computed: true,
                        },
                        "optional_computed_int": {
                                Type:     schema.TypeInt,
                                Optional: true,
                                Computed: true,
                        },
```

```hcl
resource "some_resource" "foo" {
  optional_computed_string = ""
  optional_computed_int = 0
}
```

### Expected Behavior

I expect that optional computed field empty string value will be detected as desirable and terraform will try to update this string, as it is done with integer variable being explicitly set to 0.

### Actual Behavior

Setting the optional computed field to an empty string is not reflected in a change and terraform doesn't update the computed field to an empty string.

### References

Probably related to hashicorp/terraform#21760

**Comment by kayrus** [comment] 2019-10-02 19:12
Any news on this issue?

**Comment by kayrus** [comment] 2019-11-26 12:09
@radeksimko @apparentlymart any news on this issue?

**Comment by radeksimko** [comment] 2019-12-12 08:26
Hi @kayrus 
Thank you for the report. As it was already mentioned [above](https://github.com/hashicorp/terraform-plugin-sdk/issues/173#issuecomment-525428898) this is an effect of the way Terraform 0.11 and earlier versions handled types. While 0.12 has first-class support for `null`, the SDK is still retaining backwards compatibility (which means most providers could be just recompiled without further changes to become 0.12 compatible), hence the SDK and providers still suffer from the same type-related shortcomings, despite being driven by 0.12 with the new type system.

Supporting 0.12 types (which includes `null`) in SDK is one of our current priorities. We are practically sure though that supporting these in a provider will require deprecation of <0.12 from provider's perspective as only 0.12 uses the new protocol that allows us to carry all the important details about types.

The best you can do in the meantime is to [read this blogpost](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/), share it and encourage everyone to [upgrade to 0.12](https://www.terraform.io/upgrade-guides/0-12.html).

I'm going to close this as duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/102 since it covers all types and it will allow us to keep discussion in one place.

**Closed by radeksimko** 2019-12-12 08:26 UTC
