### ISSUE TITLE
`terraform apply` command doesn't present diff between false and null

### ISSUE THREAD

**Issue by chkp-idoma** [hashicorp/terraform-plugin-sdk#273] opened 2019-12-09 12:35 UTC
### Terraform Version

```
Terraform v0.12.13
```

### Terraform Configuration Files

Custom Provider:
```go
func resourceTest() *schema.Resource {
	return &schema.Resource{
		Create: createTest,
		Read:   readTest,
		Update: updateTest,
		Delete: deleteTest,

		Schema: map[string]*schema.Schema{
			"name": &schema.Schema{
				Type:     schema.TypeString,
				Required: true,
			},
			"enable": &schema.Schema{
				Type:     schema.TypeBool,
				Optional: true,
			},
		},
	}
}

func createTest(d *schema.ResourceData, m interface{}) error {

	d.SetId("1234")
	return readTest(d, m)
}

func readTest(d *schema.ResourceData, m interface{}) error{

	_ = d.Set("name", d.Get("name"))

	return nil
}

func updateTest(d *schema.ResourceData, m interface{}) error {

	if d.HasChange("enable") {

		log.Println("enable changed")
		_ = d.Set("enable", d.Get("enable"))
	}

	return readTest(d, m)
}

func deleteTest(d *schema.ResourceData, m interface{}) error {
	return nil
}
```

Configuration file (.tf) on first `terraform apply`:
```hcl
resource "temp" "example" {
  name = "test1"
}
```
Configuration file (.tf) on second `terraform apply`:
```hcl
resource "temp" "example" {
  name = "test1"
  enable = false
}
```

### Expected Behavior

On the second run of `terraform apply`, diff should be presented:
```
Terraform will perform the following actions:
# temp.example will be updated in-place
 ~ resource "temp" "example" {
          name = "test1"
      + enable = false
    }
```

### Actual Behavior

```
temp.example: Refreshing state... [id=1234]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. build the custom provider with this single resource
2. write .tf file with the resource as shown in  "Configuration file (.tf) on first `terraform apply`:"
3. `terraform init`
4. `terraform apply`
5. change the .tf file as shown in "Configuration file (.tf) on second `terraform apply`:"
6. `terraform apply`

### Additional Context

I'm trying to show here that when TypeBool argument isn't set at the first run of `terraform apply`,
and in the second run this boolean argument is set to `false` in the configuration file, no diff shown.
It means there is no difference between `false` and `null` values in the .tfstate file.

*if this issue isn't related to this section please tell me where to open it.

**Comment by appilon** [comment] 2019-12-11 23:19
Hello @chkp-idoma unfortunately this is a known limitation of the current SDK, you cannot distinguish between Go's zero value and "unset/null". With other types, such as `TypeInt` you can work around this by using a sentinel value, such as `-1`, but with `TypeBool` unfortunately there are no tricks. We will be addressing this in future major releases of the SDK.

**Comment by chkp-idoma** [comment] 2019-12-12 06:30
Hi @appilon ,

Thanks for answering!

Is there any time estimation for this fix to be released?

**Comment by radeksimko** [comment] 2019-12-12 08:14
Hi folks,
I'm going to close this as a duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/102 as I believe it covers the exact same problem with a bit more context on why (which Alex also mentioned).

@chkp-idoma We tend not to publish any release dates, but I can say that supporting 0.12 types is one of our current priorities. We are practically sure though that supporting these in the provider will require deprecation of <0.12 from provider's perspective as only 0.12 uses the new protocol that allows us to carry all the important details about types.

The best you can do in the meantime is to [read this blogpost](https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers/), share it and encourage everyone to [upgrade to 0.12](https://www.terraform.io/upgrade-guides/0-12.html).

**Closed by radeksimko** 2019-12-12 08:14 UTC
Labels: enhancement, protocol-5-only
