### ISSUE TITLE
Panic when calling ForceNew in CustomizeDiff with Optional + Computed + ForceNew field

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform-plugin-sdk#642] opened 2020-11-16 10:21 UTC
### SDK version
```json
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk/v2",
  "Version": "v2.2.0"
}

```

### Relevant provider source code

```go
package main

import (
        "context"
        "fmt"
        "testing"

        "github.com/hashicorp/terraform-plugin-sdk/v2/diag"
        "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
        "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func TestImportTest_import(t *testing.T) {
        resource.Test(t, resource.TestCase{
                IsUnitTest: true,
                Providers: map[string]*schema.Provider{
                        "import": {
                                ResourcesMap: map[string]*schema.Resource{
                                        "import_test": {
                                                CreateContext: func(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
                                                        d.SetId("foo")

                                                        return nil
                                                },
                                                ReadContext: func(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
                                                        return nil
                                                },
                                                UpdateContext: func(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
                                                        return nil
                                                },
                                                DeleteContext: func(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
                                                        d.SetId("")

                                                        return nil
                                                },
                                                CustomizeDiff: func(ctx context.Context, d *schema.ResourceDiff, m interface{}) error {
                                                        o, n := d.GetChange("test_field")
                                                        os := o.(string)
                                                        ns := n.(string)

                                                        t.Logf("old: %q, new: %q", os, ns)
                                                        if os != "" && ns == "" {
                                                                t.Log("Forcing new")
                                                                if err := d.ForceNew("test_field"); err != nil {
                                                                        return fmt.Errorf("forcing new resource on field %q: %w", "test_field", err)
                                                                }
                                                        }

                                                        return nil
                                                },
                                                Schema: map[string]*schema.Schema{
                                                        "foo": {
                                                                Type:     schema.TypeString,
                                                                Required: true,
                                                        },
                                                        "test_field": {
                                                                Type:     schema.TypeString,
                                                                Optional: true,
                                                                ForceNew: true,
                                                                Computed: true,
                                                        },
                                                },
                                        },
                                },
                        },
                },
                Steps: []resource.TestStep{
                        {
                                Config: `
resource "import_test" "foo" {
        foo                      = "dhg"
  test_field = "bar"
}
`,
                        },
                        {
                                Config: `
resource "import_test" "foo" {
        foo                      = "dhg"
        test_field = ""
}
`,
                        },
                },
        })
}

```

### Debug Output
```
$ TF_LOG=trace go test -v ./...
=== RUN   TestImportTest_import
2020/11/16 11:20:17 [DEBUG] New state was assigned lineage "ebe4f88a-e7e5-551b-191a-e16eb80ad402"
2020/11/16 11:20:17 [DEBUG] New state was assigned lineage "c1a9bb7b-ef3c-9f76-b97b-7b0d7d731d2c"
2020/11/16 11:20:17 [DEBUG] New state was assigned lineage "34e68792-db58-5df6-66b7-56eae4875a05"
2020/11/16 11:20:18 [DEBUG] New state was assigned lineage "b7605645-5ac0-53b2-d7c9-de22150c1667"
2020/11/16 11:20:18 [DEBUG] New state was assigned lineage "c4822e5a-1641-cb59-d42f-7ffcd8961222"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x972730]

goroutine 602 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0006a0240, 0x1455760, 0xc0002da580, 0xc00009b270, 0xc0002da580, 0x0, 0x1464ac0)
        /home/invidian/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.2.0/helper/schema/grpc_provider.go:795 +0x1090
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc0006a0560, 0x1455760, 0xc0002da580, 0xc0000f8380, 0xc0006a0560, 0xc000518fc0, 0xc00066eba0)
        /home/invidian/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:314 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x1236980, 0xc0006a0560, 0x1455820, 0xc000518fc0, 0xc000114e40, 0x0, 0x1455820, 0xc000518fc0, 0xc0000aa280, 0x78)
        /home/invidian/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006bc1c0, 0x1461de0, 0xc000151e00, 0xc00028e100, 0xc000110d80, 0x1b19508, 0x0, 0x0, 0x0)
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0006bc1c0, 0x1461de0, 0xc000151e00, 0xc00028e100, 0x0)
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000122130, 0xc0006bc1c0, 0x1461de0, 0xc000151e00, 0xc00028e100)
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
FAIL    foo     1.386s
FAIL
```

### Expected Behavior

Unit test should pass.

### Actual Behavior

Code panics

### Steps to Reproduce

1. Create file `main_test.go` with the snippet above.
2. Run `go mod init foo` to initialize Go modules.
3. Run `TF_LOG=trace go test -v ./...`

### References
- Found while investigating https://github.com/packethost/terraform-provider-packet/issues/289.

**Comment by paddycarver** [comment] 2021-02-02 12:37
Hey @invidian, I believe this should be resolved in v2.4.2 of the Plugin SDK. Do you mind confirming if that's the case?

**Comment by invidian** [comment] 2021-02-02 13:13
@paddycarver yes, it seems v2.4.2 resolves the issue. v2.4.1 is still affected. I see related changes in https://github.com/hashicorp/terraform-plugin-sdk/compare/v2.4.1...v2.4.2.

I'm a bit worried, that there is no regression tests associated with that though.

**Comment by paddycarver** [comment] 2021-02-02 13:33
We had the same conversation on our end about this, actually! We ended up deciding the amount of effort required to test these changes, and the risk of breaking something else while making these changes testable, wasn't justified by the impact of the bug (it has come up twice in at least 2 years since it has been released), the expected longevity of the codebase it is in (we are attempting to move away from the code in question as we speak, because of problems like this), and how frequently the code is touched (the shims this bug exists in are avoided because of their complexity and tendency to create unintended consequences in unrelated code paths).

Normally I would agree with you and insist on a test to prevent regressions, but we weighed the tradeoffs here and decided that putting our effort into deprecating the code in question was a more valuable activity than ensuring the code in question doesn't regress at some future point.

**Comment by paddycarver** [comment] 2021-02-02 13:34
Given this issue is now fixed, I'm going to close this issue out. If you'd like to discuss whether this fix should come with a regression test, I'm happy to revisit that decision with you. I'd suggest another issue for it, however, just to help us keep track of what needs to be done still.

**Closed by paddycarver** 2021-02-02 13:34 UTC
Labels: bug

**Comment by invidian** [comment] 2021-02-02 15:22
Thanks for the explanation @paddycarver! What you're saying make sense. I guess you could just drop the test I wrote above in `test` directory on top, but that doesn't seem like an established convention in this repo, so I guess it's OK to live without it :)
