### ISSUE TITLE
Terrafrom Crash Error

### ISSUE THREAD

**Issue by stefysarah** [hashicorp/terraform-plugin-sdk#247] opened 2019-11-13 10:10 UTC
Hi,

Faced Terraform Crash when tried to run some of the terraform module.
Since it was a new deployment destroyed and then did an apply it moved ahead, but destroying is not an ideal solution.. 

We are not sure if the crash is related to the API-GW and Lambda Integration issue { To find more information on this we have looged another issue > https://github.com/hashicorp/terraform-plugin-sdk/issues/245 }

If the crash is not related to the above issue then what are the possible cause of Crash error??

please find the screenshot of Crash Error.

<img width="778" alt="TerraformCrash Error1" src="https://user-images.githubusercontent.com/57702742/68753859-b350d180-062b-11ea-9837-7bfe94cf38cd.png">
<img width="509" alt="TerraformCrash Error2" src="https://user-images.githubusercontent.com/57702742/68753860-b3e96800-062b-11ea-95ae-1951238c7c05.png">

**Comment by radeksimko** [comment] 2019-11-13 11:04
Closing as duplicate of https://github.com/hashicorp/terraform/issues/23355

**Closed by radeksimko** 2019-11-13 11:04 UTC
