### ISSUE TITLE
Clean up provider resource meta once done

### ISSUE THREAD

**Issue by pegerto** [hashicorp/terraform-plugin-sdk#132] opened 2019-02-02 00:04 UTC
Hi all,

What is the best way of closing resources in a provider after the provider end? Take for example a provider that uses a client that requires a  `Close()`, I want to connect during configure and close at the end of the execution of the provider.

Is there any prefered way? or introduce a `closeFn` at the `schema.ProviderResource` sounds interesting?

Thanks

**Comment by paddycarver** [comment] 2020-08-28 07:17
I believe this is a duplicate of #63. I'm going to close it to track the discussion there. If you believe this is in error, please reply to this issue with more information and we can reopen while we investigate. Otherwise, please subscribe to #63 for updates on this topic.

**Closed by paddycarver** 2020-08-28 07:17 UTC
Labels: enhancement, protocol-5-only
