### ISSUE TITLE
Plan-time validation based on two or more attribute values

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#203] opened 2019-10-21 14:30 UTC
Allow validation functions to take more than one attribute as input.

Proposed by @bflad.

**Comment by radeksimko** [comment] 2019-11-06 11:12
Could this be treated as duplicate of https://github.com/hashicorp/terraform-plugin-sdk/issues/233 ?

**Closed** 2019-11-08 00:41 UTC
Labels: duplicate, proposal
