### ISSUE TITLE
Step Number Missing from Binary Testing ImportState Testing

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#528] opened 2020-08-11 03:49 UTC
Different then the other recent `TestCheckFunc` report. 😉 

### SDK version

```
v2.0.1
```

### Relevant provider source code

```go
func TestAccAWSAppautoScalingPolicy_multiplePoliciesSameResource(t *testing.T) {
	var readPolicy applicationautoscaling.ScalingPolicy
	var writePolicy applicationautoscaling.ScalingPolicy

	tableName := fmt.Sprintf("tf-autoscaled-table-%s", acctest.RandString(5))
	namePrefix := fmt.Sprintf("tf-appautoscaling-policy-%s", acctest.RandString(5))

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckAWSAppautoscalingPolicyDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAWSAppautoscalingPolicy_multiplePoliciesSameResource(tableName, namePrefix),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAWSAppautoscalingPolicyExists("aws_appautoscaling_policy.read", &readPolicy),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.read", "name", namePrefix+"-read"),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.read", "resource_id", "table/"+tableName),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.read", "service_namespace", "dynamodb"),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.read", "scalable_dimension", "dynamodb:table:ReadCapacityUnits"),

					testAccCheckAWSAppautoscalingPolicyExists("aws_appautoscaling_policy.write", &writePolicy),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.write", "name", namePrefix+"-write"),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.write", "resource_id", "table/"+tableName),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.write", "service_namespace", "dynamodb"),
					resource.TestCheckResourceAttr("aws_appautoscaling_policy.write", "scalable_dimension", "dynamodb:table:WriteCapacityUnits"),
				),
			},
			{
				ResourceName:      "aws_appautoscaling_policy.read",
				ImportState:       true,
				ImportStateIdFunc: testAccAWSAppautoscalingPolicyImportStateIdFunc("aws_appautoscaling_policy.read"),
				ImportStateVerify: true,
			},
			{
				ResourceName:      "aws_appautoscaling_policy.write",
				ImportState:       true,
				ImportStateIdFunc: testAccAWSAppautoscalingPolicyImportStateIdFunc("aws_appautoscaling_policy.write"),
				ImportStateVerify: true,
			},
		},
	})
}
```

### Terraform Configuration Files

Any `ImportState(Verify)` failure I'm guessing should show this. 😄 

### Debug Output

Ask and you shall receive.

### Expected Behavior

Previously, the acceptance testing framework would output the step number, so developers can easily troubleshoot when the check failure occurred. Note the `Step 3 error` below (sorry for using a different test failure here, but hopefully you get the idea).

```
=== CONT  TestAccAWSEMRInstanceGroup_ConfigurationsJson
TestAccAWSEMRInstanceGroup_ConfigurationsJson: testing.go:684: Step 3 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) (len=1) {
(string) (len=6) "status": (string) (len=13) "RECONFIGURING"
}
(map[string]string) (len=1) {
(string) (len=6) "status": (string) (len=7) "RUNNING"
}
--- FAIL: TestAccAWSEMRInstanceGroup_ConfigurationsJson (895.42s)
```

### Actual Behavior

```
=== CONT  TestAccAWSAppautoScalingPolicy_multiplePoliciesSameResource
TestAccAWSAppautoScalingPolicy_multiplePoliciesSameResource: resource_aws_appautoscaling_policy_test.go:356: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) (len=1) {
(string) (len=18) "scalable_dimension": (string) (len=33) "dynamodb:table:WriteCapacityUnits"
}
(map[string]string) (len=1) {
(string) (len=18) "scalable_dimension": (string) (len=32) "dynamodb:table:ReadCapacityUnits"
}
--- FAIL: TestAccAWSAppautoScalingPolicy_multiplePoliciesSameResource (27.92s)
```

Which one failed? 😄  (I will file a separate bug report for this failure if it is consistent -- this worked previously in SDK v1.)

### Steps to Reproduce

After finding a test with a consistently failing `ImportStateVerify` step:

`TF_ACC=1 go test -run='TestAccXXX' -v ./...`

**Comment by paddycarver** [comment] 2020-09-12 10:07
I'm leaving this open pending the merge of #578, which gets rid of the last of our `t.Fatal`s in helper functions, at which point I think we'll have addressed all the root causes we can find of this behavior. At that point I'll close it, and if anyone finds any more instances where test step numbers are missing, we can track them in their own issue.

**Comment by paddycarver** [comment] 2020-09-30 15:46
With #578 merged, this should finally be entirely resolved.

**Closed by paddycarver** 2020-09-30 15:46 UTC
Labels: bug
