### ISSUE TITLE
`StateFunc` set on property inside a `TypeSet` block will increase single block to two blocks

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform-plugin-sdk#485] opened 2020-06-29 08:50 UTC
### SDK version

```
v1.14.0
```

### Relevant provider source code

```go
"addr": {
    Type:     schema.TypeSet,
    Optional: true,
    Elem: &schema.Resource{
        Schema: map[string]*schema.Schema{
            "country": {
                Type:     schema.TypeString,
                Required: true,
                StateFunc: func(val interface{}) string {
                    return strings.ToLower(val.(string))
                },
            },
        },
    },
},

```

### Terraform Configuration Files

```hcl
resource "demo_resource_foo" "foo" {
  name = "abc"
  addr {
    country = "China"
  }
}
```

### Debug Output

The `ResourceData` passed into callbacks (e.g. `Create` callback):

![](https://i.imgur.com/ZujzvqI.png)

### Expected Behavior

As I only configured one block in terraform config as shown above. I would expect only one such block is passed into the callbacks as `ResourceData`.

### Actual Behavior

The `ResourceData` contains two objects of `addr`.

### Steps to Reproduce

Just `terraform apply`, using my demo provider [here](https://github.com/magodo/terraform-provider-demo/tree/state_func_in_set) (note to use the `state_func_in_set` branch).

**Comment by paddycarver** [comment] 2020-08-28 07:11
I'm going to close this as a duplicate of #160. If you believe this is in error, reply to this issue with more information, and we can reopen while we investigate. Otherwise, it is recommended to watch #160 for updates on this.

**Closed by paddycarver** 2020-08-28 07:11 UTC
Labels: bug
